In [3]:
# 1. Initialize an empty array with size 2X2.

import numpy as np

matrix_empty = np.empty((2, 2))
print(matrix_empty)

[[1.80549974e-315 0.00000000e+000]
 [6.67439783e-310 5.78153247e-317]]


In [4]:
# 2. Initialize an all one array with size 4X2.

arr=np.ones((4,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
#3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

matrix_filled = np.full((3, 3), 7)
print(matrix_filled)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [40]:
#4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

sample_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_array = np.zeros_like(sample_array)
print(zeros_array)

[[0 0 0]
 [0 0 0]]


In [7]:
#5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

# First create a sample array
sample_matrix = np.array([[1, 2, 3], [4, 5, 6]])
matrix_ones_like = np.ones_like(sample_matrix)
print(matrix_ones_like)

[[1 1 1]
 [1 1 1]]


In [8]:
#6.For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

number_sequence = [1, 2, 3, 4]
numpy_array = np.array(number_sequence)
print(numpy_array)


[1 2 3 4]


In [10]:
#1.Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

number_range = np.arange(10, 50)
print(number_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
# 2. Create a 3X3 matrix with values ranging from 0 to 8.{Hint:look for np.reshape()

number_sequence = np.arange(0, 9)
square_matrix = number_sequence.reshape(3, 3)
print(square_matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
#3.Create a 3X3 identity matrix.{Hint:np.eye()}

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# 4. Create a random array of size 30 and find the mean of the array.{Hint:check for np.random.random() and array.mean() function}

random_numbers = np.random.randint(0, 100, size=30)
average_value = random_numbers.mean()
print(random_numbers)
print("Mean: ", average_value)

[39 61 55 54 47 64 16 18 66 79 96  9 90 27  2 44 34 55 26 13 81 83 34 31
 39 11 94 77 11 92]
Mean:  48.266666666666666


In [14]:
# 5. Create a 10X10 array with random values and find the minimum and maximum values.

random_grid = np.random.randint(0, 100, size=(10, 10))
minimum_value = random_grid.min()
maximum_value = random_grid.max()
print(random_grid)
print(f"Minimum value: {minimum_value}")
print(f"Maximum value: {maximum_value}")

[[11 27 25 25  0 98 23 70 11 27]
 [25 66 15 39 27  1 36 45 70 39]
 [84 67 86 41 72 77 62 53 99 97]
 [35 55 65 94 31 71 89 37 80 80]
 [30 71 20 97 91 31 19  7 99 35]
 [85 30 35 14 99 64 52 94 50 32]
 [27 42 89 42 36 62 80 29 51 54]
 [84 48 59 21 21 40 36 18 26 11]
 [11 88 97 92 32 33 40 19 90 48]
 [92 25 38 23 34 63 15 54 21 66]]
Minimum value: 0
Maximum value: 99


In [15]:
#6. Create a zero array of size 10 and replace 5th element with 1.

zero_array = np.zeros(10)
print(zero_array)
zero_array[4] = 1
print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [16]:
#7. Reverse an array arr = [1,2,0,0,4,0].

number_list = [1, 2, 0, 0, 4, 0]
print(number_list)
reversed_list = number_list[::-1]
print(reversed_list)

[1, 2, 0, 0, 4, 0]
[0, 4, 0, 0, 2, 1]


In [17]:
#8. Create a 2d array with 1 on border and 0 inside.

border_matrix = np.ones((5, 5))
border_matrix[1:-1, 1:-1] = 0
print(border_matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
#9. Create a 8X8 matrix and fill it with a checkerboard pattern.

checkerboard_grid = np.zeros((8, 8))
checkerboard_grid[1::2, ::2] = 1
checkerboard_grid[::2, 1::2] = 1
print(checkerboard_grid)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [20]:
#1. Add the two array.

x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]]);
v=np.array([9,10])
w=np.array([11,12]);

print(x)
print(y)
print(w)
print(v)
print(np.add(x,y))
print(np.add(w,v))

[[1 2]
 [3 5]]
[[5 6]
 [7 8]]
[11 12]
[ 9 10]
[[ 6  8]
 [10 13]]
[20 22]


In [21]:
#2. Subtract the two array.

print(np.subtract(x,y))
print(np.subtract(w,v))

[[-4 -4]
 [-4 -3]]
[2 2]


In [22]:
#3. Multiply the array with any integers of your choice.

print(x*10)
print(y*2)
print(v*6)
print(w*4)

[[10 20]
 [30 50]]
[[10 12]
 [14 16]]
[54 60]
[44 48]


In [23]:
#4.Find the square of each element of the array.

matrix_a = np.array([[1, 2], [3, 5]])
matrix_b = np.array([[5, 6], [7, 8]])
vector_c = np.array([9, 10])
vector_d = np.array([11, 12])

# Square each element
matrix_a_squared = np.square(matrix_a)
matrix_b_squared = np.square(matrix_b)
vector_c_squared = np.square(vector_c)
vector_d_squared = np.square(vector_d)

print("Matrix A squared:\n", matrix_a_squared)
print("Matrix B squared:\n", matrix_b_squared)
print("Vector C squared:\n", vector_c_squared)
print("Vector D squared:\n", vector_d_squared)

Matrix A squared:
 [[ 1  4]
 [ 9 25]]
Matrix B squared:
 [[25 36]
 [49 64]]
Vector C squared:
 [ 81 100]
Vector D squared:
 [121 144]


In [24]:
#5.Find the dot product between: v(and)w ; x(and)v ; x(and)y.

print(np.dot(vector_c, vector_d))
print(np.dot(matrix_a, vector_c))
print(np.dot(matrix_a, matrix_b))

219
[29 77]
[[19 22]
 [50 58]]


In [26]:
#6. Concatenate x(and)y along row and Concatenate v(and)w along column.{Hint:try np.concatenate() or np.vstack() functions.

print(np.concatenate((matrix_a, matrix_b)))
print(np.vstack((vector_c, vector_d)))

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [27]:
#7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

print(np.concatenate((matrix_a, vector_c)))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [28]:
import numpy as np

matrix_C = np.array([[3,4],[7,8]])
matrix_D = np.array([[5,3],[2,1]])

# 1. Prove A * A^-1 = I
inverse_matrix_C = np.linalg.inv(matrix_C)
identity_check = np.dot(matrix_C, inverse_matrix_C)
print("Matrix C * Matrix C^-1 =\n", identity_check)

# 2. Prove AB ≠ BA
product_CD = np.dot(matrix_C, matrix_D)
product_DC = np.dot(matrix_D, matrix_C)
print("Matrix C * Matrix D =\n", product_CD)
print("Matrix D * Matrix C =\n", product_DC)

# 3. Prove (AB)^T = B^T A^T
transpose_product = np.transpose(product_CD)
product_transposes = np.dot(np.transpose(matrix_D), np.transpose(matrix_C))
print("(Matrix C * Matrix D)^T =\n", transpose_product)
print("Matrix D^T * Matrix C^T =\n", product_transposes)

Matrix C * Matrix C^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Matrix C * Matrix D =
 [[23 13]
 [51 29]]
Matrix D * Matrix C =
 [[36 44]
 [13 16]]
(Matrix C * Matrix D)^T =
 [[23 51]
 [13 29]]
Matrix D^T * Matrix C^T =
 [[23 51]
 [13 29]]


In [29]:
#• Solve the following system of Linear equation using Inverse Methods.

coefficient_matrix = np.array([[2, -3, 1],
                              [1, -1, 2],
                              [3,  1, -1]])

constant_vector = np.array([-1, -3, 9])
inverse_coefficient_matrix = np.linalg.inv(coefficient_matrix)
solution_vector = np.dot(inverse_coefficient_matrix, constant_vector)
print("Solution [x, y, z] =", solution_vector)

Solution [x, y, z] = [ 2.  1. -2.]


In [41]:
import numpy as np
import time

In [31]:
#1. Element-wise Addition

# Create two lists of size 1,000,000
first_number_list = list(range(1000000))
second_number_list = list(range(1000000))

start_time = time.time()
sum_result_list = [num1 + num2 for num1, num2 in zip(first_number_list, second_number_list)]
end_time = time.time()

print("Python list addition time:", end_time - start_time, "seconds")

Python list addition time: 0.07557463645935059 seconds


In [32]:
first_number_array = np.arange(1000000)
second_number_array = np.arange(1000000)

start_time = time.time()
sum_result_array = first_number_array + second_number_array
end_time = time.time()

print("NumPy array addition time:", end_time - start_time, "seconds")


NumPy array addition time: 0.004422664642333984 seconds


In [34]:
start_time = time.time()
product_result_array = first_number_array * second_number_array
end_time = time.time()

print("NumPy array multiplication time:", end_time - start_time, "seconds")

NumPy array multiplication time: 0.0064160823822021484 seconds


In [35]:
#3. Dot Product

start_time = time.time()
dot_product_list = sum(num1 * num2 for num1, num2 in zip(first_number_list, second_number_list))
end_time = time.time()

print("Python list dot product time:", end_time - start_time, "seconds")

Python list dot product time: 0.08911848068237305 seconds


In [37]:
start_time = time.time()
dot_product_array = np.dot(first_number_array, second_number_array)
end_time = time.time()

print("NumPy dot product time:", end_time - start_time, "seconds")

NumPy dot product time: 0.0027501583099365234 seconds


In [38]:
#4. Matrix Multiplication (1000 × 1000)

# Create two 1000x1000 matrices using lists
first_matrix_list = [[i for i in range(1000)] for _ in range(1000)]
second_matrix_list = [[i for i in range(1000)] for _ in range(1000)]

start_time = time.time()
product_matrix_list = [[sum(element1 * element2 for element1, element2 in zip(row, column))
                  for column in zip(*second_matrix_list)]
                  for row in first_matrix_list]
end_time = time.time()

print("Python list matrix multiplication time:", end_time - start_time, "seconds")

Python list matrix multiplication time: 181.15557646751404 seconds


In [39]:
first_matrix_array = np.random.rand(1000, 1000)
second_matrix_array = np.random.rand(1000, 1000)

start_time = time.time()
product_matrix_array = np.dot(first_matrix_array, second_matrix_array)   # or first_matrix_array @ second_matrix_array
end_time = time.time()

print("NumPy matrix multiplication time:", end_time - start_time, "seconds")


NumPy matrix multiplication time: 0.06750106811523438 seconds
